### ISSUE TITLE
Server is 0.0.0.0:80

### ISSUE THREAD

**Issue by Brutal-sam** [victorrjimenezz/4PT-REPO-GUI#1]
tried to start the server many times but same result

![Capture](https://user-images.githubusercontent.com/94696121/152610787-70a83d8b-485e-4761-ad5f-a805aba817d6.JPG)

**Comment by victorrjimenezz** [comment]
that seems about right, 0.0.0.0 means the server should be listening on all IPs on the computer. Is it not working anyway?

**Comment by Brutal-sam** [comment]
getting invalid url error

**Comment by victorrjimenezz** [comment]
are you using http or https?

**Comment by Brutal-sam** [comment]
used both http/https and got an error "can't download repo.yml"
[2022-2-5_1.32.50.log](https://github.com/victorrjimenezz/4PT-REPO-GUI/files/8007102/2022-2-5_1.32.50.log)

**Comment by victorrjimenezz** [comment]
Thank you for posting the logfile, did you include the :80 in the url? Maybe that’s the issue!

PS: If so, maybe I should display on port 80 instead of :80 it because it could generate confusion

**Comment by Brutal-sam** [comment]
maybe this is because it's trying to download the repo.yml to the same directory of the other repo which already has its own yml instead of creating a new folder for the new repo
![Capture](https://user-images.githubusercontent.com/94696121/152645127-5a2a27db-6b8d-4d07-8b29-0b13d7980959.JPG)

**Comment by victorrjimenezz** [comment]
> maybe this is because it's trying to download the repo.yml to the same directory of the other repo which already has its own yml instead of creating a new folder for the new repo
> ![Capture](https://user-images.githubusercontent.com/94696121/152645127-5a2a27db-6b8d-4d07-8b29-0b13d7980959.JPG)

It seems to me from the picture that you’re typing :80 when typing the URL, what I meant is that the URL should be written without the :80

The :80 just indicates that is running on the default 80 port

also, 127.0.0.1 points to the Ps4, the URL should be the PC address

**Comment by victorrjimenezz** [comment]
anyways, I think it is not clear enough on the GUI what the IP is, the :80 part might induce to confusion, I will change it today and release another update

**Comment by Brutal-sam** [comment]
yeah that will be better :) great tool

**Comment by victorrjimenezz** [comment]
thank you :)
Just released the new version, should be working now :)
